### PR TITLE
Correlator.

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by kakkoyun** [comment]
@bwplotka What is missing here? Shall we just merge?

**Comment by bwplotka** [comment]
I am only changing "correlator" itself, so feel free to merge other stuff in mean time @kakkoyun in observability example.

**Comment by bwplotka** [comment]
I will merge this once something will be there

**Comment by bwplotka** [comment]
Changed direction a bit, will push to master

**Pull request closed without merging**
